import car1 from "../../Images/banner.png";

export const cars = [
    {
      name: "Volvo",
      body: "Sedan",
      passengers: 4,
      type: "Manual",
      ratings: 4.5,
      charge: 15,
      condition: "AC",
      img: car1,
    },
    {
      name: "Hundyai",
      body: "Sedan",
      passengers: 4,
      type: "Manual",
      ratings: 4.5,
      charge: 20,
      condition: "AC",
      img: car1,
    },
    {
      name: "BMW",
      body: "Sedan",
      passengers: 4,
      type: "Manual",
      ratings: 4.5,
      charge: 25,
      condition: "AC",
      img: car1,
    },
    {
      name: "Volvo",
      body: "Sedan",
      passengers: 4,
      type: "Manual",
      ratings: 4.5,
      charge: 22,
      condition: "AC",
      img: car1,
    },
    {
      name: "Nissan",
      body: "Sedan",
      passengers: 4,
      type: "Manual",
      ratings: 4.5,
      charge: 18,
      condition: "AC",
      img: car1,
    },
    {
      name: "Nissan",
      body: "Sedan",
      passengers: 4,
      type: "Manual",
      ratings: 4.5,
      charge: 20,
      condition: "AC",
      img: car1,
    },
  ];